#!/bin/sh
# post-install - Install the service number, if it doesn't exist.
# Copyright (C) 2013 PalominoDB, Inc.
# 
# You may contact the maintainers at eng@palominodb.com.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if ! grep -q mysql-zrm /etc/services ; then
  echo Adding 25300/tcp to /etc/services
  cp /etc/services /etc/services.pkgsave
  echo 'mysql-zrm       25300/tcp  # mysql-zrm socket server' >> /etc/services
fi

# Install the inetd service
echo Adding mysql-zrm to /etc/inetd.conf
echo You\'ll need to reload/restart inetd for this to be visible.
sed -i .pkgsave -e '/^mysql-zrm/d' /etc/inetd.conf
echo 'mysql-zrm stream tcp nowait mysql /usr/share/mysql-zrm/plugins/socket-server.palomino.pl' >> /etc/inetd.conf
