#!/bin/sh
# requirements
# Copyright (C) 2013 PalominoDB, Inc.
# 
# You may contact the maintainers at eng@palominodb.com.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [ -z "$INNOBACKUPEX_PATH" ]; then
  which innobackupex-1.5.1 >/dev/null
  if [ ! $? ]; then
    echo "Unable to find innobackupex-1.5.1 in path."
    exit 1
  fi
fi

MIN_XTRA_VERSION=1.0
XTRA_VERSION=$(xtrabackup --version | head -n1 | awk '{print $3}')

if echo '!'"$XTRA_VERSION >= $MIN_XTRA_VERSION" | bc -lq >/dev/null ; then
  echo "Minimum version not met for xtrabackup."
fi

# Only support installs rooted at /usr, for now.
perl -I/usr/lib/mysql-zrm -MZRM::SnapshotCommon -e '1;'
if [ ! $? ]; then
  echo "Unable to find ZRM::SnapshotCommon at /usr/lib/mysql-zrm."
  exit 1
fi

echo Everything looks fine dependency-wise, proceeding with installation.
exit 0
