#!/bin/sh

if [ -z "$INNOBACKUPEX_PATH" ]; then
  which innobackupex-1.5.1 >/dev/null
  if [ ! $? ]; then
    echo "Unable to find innobackupex-1.5.1 in path."
    exit 1
  fi
fi

MIN_XTRA_VERSION=1.0
XTRA_VERSION=$(xtrabackup --version | head -n1 | awk '{print $3}')

if echo '!'"$XTRA_VERSION >= $MIN_XTRA_VERSION" | bc -lq >/dev/null ; then
  echo "Minimum version not met for xtrabackup."
fi

# Only support installs rooted at /usr, for now.
perl -I/usr/lib/mysql-zrm -MZRM::SnapshotCommon -e '1;'
if [ ! $? ]; then
  echo "Unable to find ZRM::SnapshotCommon at /usr/lib/mysql-zrm."
  exit 1
fi

echo Everything looks fine dependency-wise, proceeding with installation.
exit 0
